name: Python Package Test Workflow

# Trigger the workflow on pushes to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-sequentially:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Python 3.8
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies for Python 3.8
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests for Python 3.8
        run: |
          pip install pytest
          pytest

      # Python 3.9
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies for Python 3.9
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests for Python 3.9
        run: |
          pip install pytest
          pytest

      # Python 3.10
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies for Python 3.10
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests for Python 3.10
        run: |
          pip install pytest
          pytest

      # Python 3.11
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies for Python 3.11
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests for Python 3.11
        run: |
          pip install pytest
          pytest
