name: Python Package Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-sequentially:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Upgrade pip and install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run tests for Python 3.8
        run: pytest tests/  # Adjusted to look for tests in the 'tests' folder
